### ISSUE TITLE
Dear BzzzThe18th,

### ISSUE THREAD

**Issue by Antmanmodisnotworkingy** [BzzzThe18th/Ant-Monke-PC#3]
I am so sorry.  My drunk ass fucking wrote that piece of satire.  Didn't even know I wrote it until you contacted me.  I'm sorry bro. I also want to ask what are your pronouns?  I could have been misgendering you this entire time.   I just feel sick when thinking about this issue.  I can't believe that we are talking about a fucking kid game.  I hope you understand that I love your content and you.   Have a great rest of 2023!  

 From, GreenGorilla

**Comment by reffieeeeeeeeeeeeeeee** [comment]
Fuck you cunt

**Comment by reffieeeeeeeeeeeeeeee** [comment]
Stop bitching

**Comment by Antmanmodisnotworkingy** [comment]
Who the fuck are you

**Comment by reffieeeeeeeeeeeeeeee** [comment]
Suck my dick you fat fuckwad. No one loves your fatherless bitch ass.

**Comment by Antmanmodisnotworkingy** [comment]
What

**Comment by Antmanmodisnotworkingy** [comment]
Where is this hate coming from?

**Comment by Antmanmodisnotworkingy** [comment]
"You're"

**Comment by reffieeeeeeeeeeeeeeee** [comment]
Well your grammer is shit and your shit.

**Comment by Antmanmodisnotworkingy** [comment]
You messed up again.  Its "You're"

**Comment by reffieeeeeeeeeeeeeeee** [comment]
Smartass you gay as hell nigger.

**Comment by Antmanmodisnotworkingy** [comment]
Bruh

**Comment by Antmanmodisnotworkingy** [comment]
Why the fuck do you even give a shit?

**Comment by Antmanmodisnotworkingy** [comment]
Stop trying to get clout on the internet

**Comment by reffieeeeeeeeeeeeeeee** [comment]
NIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGER

**Comment by Antmanmodisnotworkingy** [comment]
Bro you definitely are not black

**Comment by reffieeeeeeeeeeeeeeee** [comment]
Your ip adress is 207.192.231.11

**Comment by reffieeeeeeeeeeeeeeee** [comment]
You online loser?

**Comment by Antmanmodisnotworkingy** [comment]
What

**Comment by Antmanmodisnotworkingy** [comment]
What now

**Comment by Antmanmodisnotworkingy** [comment]
Why the hell you getting so angry over a kid game?

**Comment by reffieeeeeeeeeeeeeeee** [comment]
This half ass piece of shit you wrote can suck my dick.   No one loves a rotting prick like you.

**Comment by Antmanmodisnotworkingy** [comment]
I can right my wrongs when you can't do shit other than whine on the internet.

**Comment by Antmanmodisnotworkingy** [comment]
It's not perfect but I tried to apologize and maybe Bzzz will forgive me.

**Comment by Antmanmodisnotworkingy** [comment]
I'm still struggling with addiction man so mind your own business.

**Comment by BzzzThe18th** [comment]
![image](https://user-images.githubusercontent.com/69125495/236065661-d6f82f7b-9644-4849-929a-f8415025d9bd.png)
